apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: 'posts.com'
      http:
        paths:
          - pathType: Prefix
            path: '/posts'
            backend:
              service:
                name: posts-clusterip-srv
                port:
                  number: 4000
          - pathType: Prefix
            path: '/posts/:id/comments'
            backend:
              service:
                name: comments-srv
                port:
                  number: 4001
          - pathType: Prefix
            path: '/posts'
            backend:
              service:
                name: query-srv
                port:
                  number: 4002
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
